### ISSUE TITLE
How to get lat long from Prediction?

### ISSUE THREAD

**Issue by DineshKachhot** [lejard-h/flutter_google_places#27] opened 2018-10-31 02:30 UTC
Can we get lat long from Prediction object ?

there is no Location object in Prediction constructor:-

  final String description;
  final String id;
  final List<Term> terms;

  /// JSON place_id
  final String placeId;
  final String reference;
  final List<String> types;

  /// JSON matched_substrings
  final List<MatchedSubstring> matchedSubstrings;

What I have to do to get Location ?

**Comment by lejard-h** [comment] 2018-11-10 12:10
duplicate of https://github.com/lejard-h/flutter_google_places/issues/25

**Closed by lejard-h** 2018-11-10 12:10 UTC

**Comment by savasadar** [comment] 2020-03-12 13:08
```
Future<Null> displayPrediction(Prediction p, ScaffoldState scaffold) async {
  if (p != null) {
    // get detail (lat/lng)
    PlacesDetailsResponse detail = await _places.getDetailsByPlaceId(p.placeId);
    final lat = detail.result.geometry.location.lat;
    final lng = detail.result.geometry.location.lng;

    scaffold.showSnackBar(
      SnackBar(content: Text("${p.description} - $lat/$lng")),
    );
  }
}
```
